version: '3.8'
services:
  eureka-service:
    image: eureka-service
    restart: always
    container_name: eureka-service
    ports:
      - '8761:8761'
    networks:
      - 'config-network'
networks:
  config-network:
    external: true
